print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Lex/Documents/IGME-219---Final-Project/UnityProject (Latest)/Assets/Sean's Models/sjm_Mace.mb"`)
{		
	file -o "/Users/Lex/Documents/IGME-219---Final-Project/UnityProject (Latest)/Assets/Sean's Models/sjm_Mace.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Lex/Documents/IGME-219---Final-Project/UnityProject (Latest)/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Lex/Documents/IGME-219---Final-Project/UnityProject (Latest)/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Lex/Documents/IGME-219---Final-Project/UnityProject (Latest)/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
